// Generated by CoffeeScript 1.6.2
(function() {
  var Huffman;

  Huffman = {
    treeFromText: function(text) {
      var builder;

      builder = new Huffman.TreeBuilder(text);
      return builder.build();
    }
  };

}).call(this);
